export const EMAIL_INPUT = 'EMAIL_INPUT';
export const PASSWORD_INPUT = 'PASSWORD_INPUT';
export const SUBMIT_FORM_PENDING = 'SUBMIT_FORM_PENDING';
export const SUBMIT_FORM_SUCCESS = 'SUBMIT_FORM_SUCCESS';
export const SUBMIT_FORM_FAILED = 'SUBMIT_FORM_FAILED';
export const TOGGLE_LOG_USER = 'TOGGLE_LOG_USER';
export const LOG_OUT_USER = 'LOG_OUT_USER';
